version: "2.1"
services:
  # Jellyfin to watch movies and series
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1100       # change if needed
      - PGID=2000       # change if needed
      - TZ=Europe/Paris # change if needed
    volumes:
      - /mnt/SSD-APP/appdata/jellyfin:/config     # change to your config directory
      - /mnt/RAID-WD-2To/Data/Films:/data/movies  # change to your movies directory
    ports:
      - 9096:8096 # for web interface (for testing)
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: always

networks:
  default:
    external: true
    name: docker_network